apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: hatena-intern-2021
build:
  artifacts:
  - image: 988008726365.dkr.ecr.ap-northeast-1.amazonaws.com/hatena-intern-2021-account
    context: services/account
  - image: 988008726365.dkr.ecr.ap-northeast-1.amazonaws.com/hatena-intern-2021-blog
    context: services/blog
  - image: 988008726365.dkr.ecr.ap-northeast-1.amazonaws.com/hatena-intern-2021-renderer-go
    context: services/renderer-go
  - image: hatena-intern-2021-fetcher
    context: services/fetcher
  local:
    push: true
    useBuildkit: true
deploy:
  statusCheckDeadlineSeconds: 180
  kubeContext: hatena-intern-2021
  kustomize:
    paths:
    - k8s
